# version: '3'

# services:
#   backend:
#     build:
#      context: ./Backend
#      dockerfile: Dockerfile
#     ports:
#       - '3333:3333'
#     container_name: backend

#   frontend:
#     build:
#       context: ./my-app
#       dockerfile: Dockerfile
#     ports:
#       - '3000:3000'
#     container_name: frontend

#   nginx:
#     build:
#       context: ./nginx
#       dockerfile: Dockerfile
#     ports:
#       - '80:80'
#     container_name: nginx

version: '3'

services:
  nginx:
    depends_on:
      # - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./Backend:/app
    ports:
      - "3333:3333"

  client:
    stdin_open: true
    build:
      context: ./my-app
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./my-app:/app